version: "3.9"
services:
  dev:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    working_dir: '/app'
    volumes:
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./slides:/app/slides
      - ./main.js:/app/main.js
      - ./style.css:/app/style.css
      - ./vite.config.js:/app/vite.config.js

  make-static:
    build: .
    command: "npm run build"
    working_dir: '/app'
    volumes:
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./slides:/app/slides
      - ./main.js:/app/main.js
      - ./style.css:/app/style.css
      - ./vite.config.js:/app/vite.config.js
      - ./public:/app/dist

  serve:
    build: .
    command: "npm run serve"
    ports:
      - "4173:4173"
    working_dir: '/app'
    volumes:
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./slides:/app/slides
      - ./main.js:/app/main.js
      - ./style.css:/app/style.css
      - ./vite.config.js:/app/vite.config.js
      - ./public:/app/dist
